# AUTOGENERATED! DO NOT EDIT! File to edit: 00_beproductive.ipynb (unless otherwise specified).

__all__ = ['main', 'parse_arguments', 'in_notebook']

# Cell
from .blocker import *
from .pomodoro import *
import argparse

# Cell
def main(action):
    if action == 'block' or action == None:
        blocker = Blocker()
        if blocker.adminrights:
            blocker.block(notify=True)
    elif action == 'unblock':
        blocker = Blocker()
        if blocker.adminrights:
            blocker.unblock(notify=True)
    elif action == 'pomodoro':
        pomodoro()
    elif action == 'pomodoro_test': # Testing pomodoro functionality with short times
        pomodoro(1/60, 1/60, 2)

# Cell
def parse_arguments():
    parser = argparse.ArgumentParser(description="Block addictive websites. Study with the Pomodoro technique.")
    parser.add_argument('action', help='Block or unblock websites, or start a Pomodoro session. ', \
                        nargs='?', choices=['block', 'unblock', 'pomodoro'])
    args = parser.parse_args()
    return args

# Cell
def in_notebook():
    try:
        from IPython import get_ipython
        if 'IPKernelApp' not in get_ipython().config:  # pragma: no cover
            return False
    except ImportError:
        return False
    return True

# Cell
if __name__ == '__main__' and not in_notebook():
    args = parse_arguments()
    main(args.action)