# AUTOGENERATED! DO NOT EDIT! File to edit: 03_blocklist.ipynb (unless otherwise specified).

__all__ = ['BLOCKLIST']

# Cell
BLOCKLIST = [
    "twitter.com",
    "youtube.com",
    "facebook.com",
    "instagram.com",
    "reddit.com",
    "netflix.com",
    "amazon.com",
    "linkedin.com"
]