# AUTOGENERATED! DO NOT EDIT! File to edit: 01_pomodoro.ipynb (unless otherwise specified).

__all__ = ['WORK', 'BREAK', 'POMODOROS']

# Cell
from time import sleep
import beproductive.blocker
import sys

WORK = 25
BREAK = 5
POMODOROS = 4